### ISSUE TITLE
Cannot connect to Mongo 3.2

### ISSUE THREAD

**Issue by hungtd9** [cloudinsights/play-salat#1]
Get problem when connecting to Mongo 3.2 with credentials, please change the createMongoCRCredential on Plugin

**Comment by markusz** [comment]
For those who were brought here by google, the following **workaround** solves the problem for me
1. Add the following to your dependencies:

```
"org.mongodb" %% "casbah" % "2.8.2",
"com.novus" %% "salat" % "1.9.9"
```

and remove

```
"net.cloudinsights" %% "play-plugins-salat" % "1.5.9" 
```
1. Copy the files in `https://github.com/cloudinsights/play-salat/tree/master/src/main/scala/se/radley/plugin/salat` into your project, i.e. in `plugins/salat`
2. Change the imports from `se.radley.plugin.salat._` to `plugins.salat._`
3. And most important: change `MongoCredential.createMongoCRCredential(u, dbName, p.toArray)` to `MongoCredential.createCredential(u, dbName, p.toArray)` in `SalatPlugin.scala:34`
